INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES
	('weaclip', 'Weapon Clip', 1, 0, 1),
	('weabox', 'Weapon Box', 2, 0, 1),
	('pistolclip', 'Pistol Clip', 1, 0, 1),
	('smgclip', 'SMG Clip', 1, 0, 1),
	('shotgunclip', 'Shotgun Clip', 1, 0, 1),
	('rifleclip', 'Rifle Clip', 1, 0, 1),
	('mgclip', 'MG Clip', 1, 0, 1),
	('sniperclip', 'Sniper Clip', 1, 0, 1),
	('throwableclip', 'Throwable Clip', 1, 0, 1),
	('scope', 'Scope', 1, 0, 1),
	('grip', 'Grip', 1, 0, 1),
	('flashlight', 'Flashlight', 1, 0, 1),
	('clip_extended', 'Extended Clip', 1, 0, 1),
	('suppressor', 'Suppressor', 1, 0, 1),
	('attachment_remover', 'Attechment Remover', 1, 0, 1),
	('luxary_finish', 'Luxury Finish', 1, 0, 1),
	('tint_green', 'Green', 1, 0, 1),
	('tint_gold', 'Gold', 1, 0, 1),
	('tint_pink', 'Pink', 1, 0, 1),
	('tint_army', 'Army', 1, 0, 1),
	('tint_lspd', 'LSPD', 1, 0, 1),
	('tint_orange', 'Orange', 1, 0, 1),
	('tint_platinum', 'Platinum', 1, 0, 1)
;