dnz_system = {}
-- Security
dnz_system.Token = "DNZ281969325988625750" -- Security Token of dnz_amenuv2 from https://license.dnz.wtf
dnz_system.getSharedObject = "esx:getSharedObject" -- Shared Object Trigger
dnz_system.ScriptName = 'dnz_amenuv2' -- Scriptname (You cannot change the Scriptname)
-- Webhooks
dnz_system.webhook = {
    name = "dnzscripts", -- Webhook Bot Name
    icon = "https://cdn.discordapp.com/attachments/891656387917123634/955906604363051018/dnz_2.png", -- Your Logo
    color = 16711680, -- All Color Codes: https://bit.ly/3NC8yto
    webhooks = {
        allwebhooks = "https://discord.com/api/webhooks/1055495106301538304/reYosrKtlbXCIjxdiA93AGt49it-36-RxVJELFNetjAIXGZI8FGcYPeeh3hKLIawufny",  -- Webhook for all Logs
        givelog = "", -- Give Log
        carlogs = "", -- Vehicle Log
        adminlogs = "", -- Admin Logs
        screenshots = {
            screenshotlog = "", -- Screenshotlog
            savelog = "https://discord.com/api/webhooks/1055495317295997059/q0Zr9pzKoF4Natrixeg3zTfVh_Q3pD3lzFrtmEK43I-gVyKqeKocRH1ltzYCHnKDYueN", -- [NEEDED] (Not integrated in All-Log) Just a Webhook for the HTML Screenshot in the Script. 
        },
        banlog = "", -- Ban/Unban Log
        kicklog = "", -- Kick Log
        warnlog = "", -- Warn Log
        teamchatlog = "", -- Ingame Teamchat Log
        useractionlog = "", -- User Actions Log
    }
}
Config = {}
-- Revive Trigger
Config.ReviveTrigger = "gl-ambulance:revivePlayer"
--Permissions | Which Group can what?
Config.Permissions = {
    openmenu = {"admin", "dev", "mod"},
    aduty = {"admin", "dev", "mod"},
    deleteallcars = {"admin", "dev"},
    espshowasadmin = {"admin", "dev"},
    noclip = {"admin", "dev", "mod"},
    suicide = {"admin", "dev"},
    reviveself = {"admin", "dev"},
    invisible = {"admin", "dev"},
    healself = {"admin", "dev"},
    armourself = {"admin", "dev"},
    godmode = {"admin", "dev"},
    allweapons = {"admin", "dev"},
    removeallweapons = {"admin", "dev"},
    tpm = {"admin", "dev", "mod"},
    tpc = {"admin", "dev"},
    reviveall = {"admin", "dev"},
    deleteallpeds = {"admin", "dev"},
    kickall = {"admin", "dev"},
    deleteallobjects = {"admin", "dev"},
    giveitem = {"admin", "dev"},
    giveweapon = {"admin", "dev"},
    givemoney = {"admin", "dev"},
    deletevehicle = {"admin", "dev"},
    spawnvehicle = {"admin", "dev"},
    flipvehicle = {"admin", "dev"},
    repairvehicle = {"admin", "dev"},
    teamchat = {"admin", "dev", "mod"},
    fulltunevehicle = {"admin", "dev"},
    godmodevehicle = {"admin", "dev"},
    espall = {"admin", "dev"},
    espnames = {"admin", "dev", "mod"},
    espinfo = {"admin", "dev"},
    espbox = {"admin", "dev"},
    esplines = {"admin", "dev"},
    espdebug = {"admin", "dev"},
    freeze = {"admin", "dev"},
    revivesomeone = {"admin", "dev"},
    gotosomeone = {"admin", "dev"},
    bring = {"admin", "dev", "mod"},
    screenshot = {"admin", "dev", "mod"},
    spectate = {"admin", "dev"},
    kick = {"admin", "dev"},
    warn = {"admin", "dev"},
    deletewarn = {"admin", "dev"},
    seeip = {"admin", "dev"},
    ban = {
        ban = {"admin", "dev"},
        unban = {"admin", "dev"},
        one_day = {"admin", "dev"},
        three_days = {"admin", "dev"},
        one_week = {"admin", "dev"},
        two_weeks = {"admin", "dev"},
        three_weeks = {"admin", "dev"},
        one_month = {"admin", "dev"},
        three_months = {"admin", "dev"},
        six_months = {"admin", "dev"},
        permanent = {"admin", "dev"}
    },
}
-- Default Settings
Config.Amenu = {
    noclipcommand = "noclip",
    adutycommand = "aduty",
    openmenucommand = "amenu",
    vanishcommand = "vanish",
    teamchatcommand = "tc", 
    teamchatenabled = true,
    needtobeinaduty = false,
    openkey = "INSERT",
    noclipkey = "",
    vanishkey = "",
    adutykey = "",
}
-- Aduty Settings
Config.Aduty = {
    godmode = true,
    invisiblenoclip = true,
    superjump = false,
    fastwalk = false,
    noclipspeed = 1,
    namesdistance = 500,
    infodistance = 500,
    noclipsound = false,
}
-- Use the build in Notify?
Config.builtinnotify = true
-- Own Notify
Config.ownnotify = function(title, msg)
    -- BSP. TriggerEvent("dnz_amenuv2:notify", title, msg)
end
--Translations for Groups
function groupnames(group)
    groupname = groupname
    if group == "admin" then
        groupname = "Admin"
    elseif group == "dev" then
        groupname = "Developer"
    elseif group == "mod" then
        groupname = "Mod"
    end
    TriggerEvent("sendgroups", groupname)
end
-- Language
Config.Lang = "de"
Config.Language = {
	["de"] = {
        ["toptitle"] = "HopeLife<span>RP<span>",
        ["generalleft"] = "General",
        ["infobtnleft"] = "[Info] Spieler",
        ["actionsbtnleft"] = "[Aktionen] Spieler",
        ["banbtnleft"] = "Banliste",
        ["generaltop"] = "GENERAL",
        ["actionstext"] = "AKTIONEN",
        ["playerinfotop"] = "SPIELER INFORMATIONEN",
        ["playeractionstop"] = "SPIELER AKTIONEN",
        ["playeractionstopsmall"] = "Aktionen gegen Spieler ergreifen.",
        ["playerinfotopsmall"] = "Überprüfe Spieler Informationen",
        ["generalsmall"] = "Jede Berechtigung kann angepasst werden.",
        ["freezebtn"] = "EINFRIEREN",
        ["revivesomeonebtn"] = "REVIVE",
        ["1day"] = "1 Tag",
        ["3day"] = "3 Tage",
        ["1weeks"] = "1 Woche",
        ["2weeks"] = "2 Wochen",
        ["3weeks"] = "3 Wochen",
        ["1month"] = "1 Monat",
        ["3months"] = "3 Monate",
        ["6months"] = "6 Monate",
        ["perma"] = "Permanent",
        ["reasontext"] = "GRUND",
        ["banlisttext"] = "BANLISTE",
        ["banlisttextsmall"] = "Alle bisher getätigten Bans",
        ["banidtext"] = "BAN ID",
        ["nametext"] = "NAME",
        ["steamtext"] = "STEAM",
        ["bytext2"] = "AUSGEFÜHRT VON",
        ["reasontext3"] = "GRUND",
        ["lengthtext3"] = "LÄNGE",
        ["datetext3"] = "DATUM/ZEIT",
        ["deletetext3"] = "LÖSCHEN",
        ["banlengthtext"] = "BAN LÄNGE",
        ["gotobtn"] = "GOTO",
        ["bringbtn"] = "BRING",
        ["screenshotbtn"] = "SCREENSHOT",
        ["spectatebtn"] = "ZUSCHAUEN",
        ["kickbtn"] = "KICK",
        ["warnbtn"] = "WARN",
        ["banbtn"] = "BAN",
        ["givetop"] = "Geben",
        ["warnlist"] = "WARNLISTE",
        ["infotext"] = "INFORMATIONEN",
        ["actiontext"] = "AKTION",
        ["bytext"] = "AUSGEFÜHRT VON",
        ["reasontext"] = "GRUND",
        ["datetext"] = "DATUM/ZEIT",
        ["giveitemsada"] = "Geben",
        ["giveweaponsada"] = "Geben",
        ["givemoneysada"] = "Geben",
        ["itemnametop"] = "Item Name",
        ["itemamounttop"] = "Anzahl",
        ["weaponnametop"] = "Waffen Name",
        ["weaponammotop"] = "Munition",
        ["moneyamountop"] = "Geld Anzahl",
        ["moneytyptop"] = "Typ",
        ["moneytypcash"] = "Bargeld",
        ["moneytypbank"] = "Bank",
        ["moneytypblack"] = "Schwarzgeld",
        ["vehicletop"] = "FAHRZEUG",
        ["vehiclenametop"] = "Name",
        ["vehiclespawntop"] = "Spawnen",
        ["vehiclefliptop"] = "Fahrzeug drehen",
        ["vehiclefulltop"] = "Fulltune",
        ["vehiclegodtop"] = "Godmode",
        ["vehiclereptop"] = "Reparieren",
        ["vehicledeltop"] = "Löschen",
        ["admintop"] = "ADMIN",
        ["adutysada"] = "On/Off Duty",
        ["tpmsada"] = "TP to Marker",
        ["tpcsada"] = "TP to Coords",
        ["reviveallsada"] = "Revive all",
        ["delcarsada"] = "Alle Autos löschen",
        ["delobjsada"] = "Alle Objects Löschen",
        ["delpedssada"] = "Alle Peds Löschen",
        ["kickallsada"] = "Alle Spieler kicken",
        ["cheetostop"] = "ESP",
        ["cheetosesptop"] = "ESP",
        ["cheetosenabletop"] = "Enable",
        ["cheetosnamestop"] = "Names",
        ["cheetosinfotop"] = "Info",
        ["cheetosboxtop"] = "Box",
        ["cheetoslinestop"] = "Lines",
        ["cheetosdebugtop"] = "Debug",
        ["cheetosnocliptop"] = "Noclip",
        ["cheetossuicidetop"] = "Suicide",
        ["cheetosrevivetop"] = "Revive",
        ["cheetosinvisibletop"] = "Unsichtbar",
        ["cheetoshealtop"] = "Heal",
        ["cheetosarmortop"] = "Rüstung",
        ["cheetosgodtop"] = "Godmode",
        ["cheetosallweaponstop"] = "Alle Waffen",
        ["cheetosremweatop"] = "Alle Waffen löschen",
        ["giveitem"] = "Du hast ",
        ["warn"] = "Du wurdest von ",
        ["warn2"] = "verwarnt Grund: ",
        ["warn3"] = "Du hast: ",
        ["warn4"] = "gewarnt Grund: ",
        ["bannedmessage"] = "Du bist von diesem Server gebannt!",
        ["bannedmessage2"] = "Du wurdest von diesem Server gebannt!",
        ["bannedperma"] = "Du bist permanent von diesem Server gebannt!",
        ["bannedby"] = "Gebannt von ",
        ["bannedreason"] = "Grund: ",
        ["bannedid"] = "Ban ID: ",
        ["bannedduration"] = "Gebannt bis: ",
        ["bannedinvitetext"] = "Für mehr Informationen und unseren Support Joine:",
        ["bannedinvite"] = "discord.gg/dnzscripts",
        ["noreason"] = "Du hast keinen Grund gegeben.",
        ["youbanned"] = "Du hast: ",
        ["youbannedreason"] = "gebannt Grund: ",
        ["youunbanned"] = "Du hast entbannt: Ban ID: ",
        ["noclip"] = "Noclip: Aktiviert",
        ["noclip2"] = "Noclip: Deaktiviert",
        ["notinduty"] = "Du bist nicht im Aduty",
        ["notallowed"] = "Du bist dazu nicht berechtigt.",
        ["consoleaccses"] = "Befehl kann nicht verwendet werden, Konsolenzugriff erforderlich",
        ["lengthnotallowed"] = "Du bist nicht Berechtigt diese Länge zu Bannen",
        ["nooneselected"] = "Du hast niemanden ausgewählt.",
        ["gotfreezed"] = "Du wurdest ent/eingefroren von: ",
        ["freezed"] = "Du hast ent/eingefroren: ",
        ["revive"] = "Du hast wiederbelebt ",
        ["gotrevived"] = "Du wurdest wiederbelebt von ",
        ["nomarker"] = "Du hast keinen Wegpunkt gesetzt",
        ["nocoords"] = "Du hast nicht alle Lücken ausgefüllt.",
        ["youkicked"] = "Du hast ",
        ["screenshotwaiting"] = "Screenshot lädt...",
        ["screenshotdone"] = "Screenshot wurde geladen.",
        ["youkickedreason"] = " gekickt Grund: ",
        ["aduty"] = "Du bist nun im Aduty.",
        ["noaduty"] = "Du bist nun nichtmehr im Aduty.",
        ["vehiclegodmode"] = "Fahrzeug Godmode aktiviert.",
        ["notvehiclegodmode"] = "Fahrzeug Godmode deaktiviert.",
        ["godmode"] = "Godmode aktiviert.",
        ["notgodmode"] = "Godmode deaktiviert.",
        ["noinput"] = "Du hast keinen Spawnnamen eingetragen.",
        ["vanish"] = "Du bist nun Unsichtbar",
        ["vanish2"] = "Du bist nun nichtmehr Unsichtbar",
        ["youdeletedwarn"] = "Du löscht den Warn:",
        ["banlistplaceholder"] = "Suchen...",
        ["playersearchplaceholder"] = "Suche nach ID oder Name...",
        ["reasonplaceholder"] = "Grund für Kick, Warn, Ban",
        ["errorweapon"] = "Diese Waffe existiert nicht.",
	},
    ["en"] = {
        ["toptitle"] = "DNZ.<span>WTF<span>",
        ["generalleft"] = "General",
        ["infobtnleft"] = "[Info] Players",
        ["actionsbtnleft"] = "[Actions] Players",
        ["banbtnleft"] = "Banlist",
        ["generaltop"] = "GENERAL",
        ["playeractionstop"] = "PLAYER ACTIONS",
        ["playeractionstopsmall"] = "Take actions against players",
        ["playerinfotop"] = "PLAYER INFORMATION",
        ["actionstext"] = "ACTIONS",
        ["playerinfotopsmall"] = "Check players information",
        ["generalsmall"] = "You can change Permission for each group.",
        ["infotext"] = "INFORMATION",
        ["actiontext"] = "ACTION",
        ["bytext"] = "EXECUTED BY",
        ["reasontext"] = "REASON",
        ["datetext"] = "DATE/TIME",
        ["freezebtn"] = "FREEZE",
        ["revivesomeonebtn"] = "REVIVE",
        ["gotobtn"] = "GOTO",
        ["bringbtn"] = "BRING",
        ["screenshotbtn"] = "SCREENSHOT",
        ["spectatebtn"] = "SPECTATE",
        ["kickbtn"] = "KICK",
        ["warnbtn"] = "WARN",
        ["banbtn"] = "BAN",
        ["banlisttext"] = "BANLIST",
        ["banlisttextsmall"] = "All bans made so far",
        ["banidtext"] = "BAN ID",
        ["nametext"] = "NAME",
        ["steamtext"] = "STEAM",
        ["bytext2"] = "EXECUTED BY",
        ["reasontext3"] = "REASON",
        ["lengthtext3"] = "LENGTH",
        ["datetext3"] = "DATE/TIME",
        ["deletetext3"] = "DELETE",
        ["1day"] = "1 day",
        ["3day"] = "3 day",
        ["1weeks"] = "1 week",
        ["2weeks"] = "2 weeks",
        ["3weeks"] = "3 weeks",
        ["1month"] = "1 month",
        ["3months"] = "3 months",
        ["6months"] = "6 months",
        ["perma"] = "Permanent",
        ["reasontext"] = "Reason",
        ["banlengthtext"] = "BAN LENGTH",
        ["givetop"] = "GIVE",
        ["giveitemsada"] = "GIVE",
        ["giveweaponsada"] = "GIVE",
        ["givemoneysada"] = "GIVE",
        ["itemnametop"] = "Item Name",
        ["itemamounttop"] = "Amount",
        ["warnlist"] = "WARNLIST",
        ["weaponnametop"] = "Weapon Name",
        ["weaponammotop"] = "Ammo",
        ["moneyamountop"] = "Money Amount",
        ["moneytyptop"] = "Type",
        ["moneytypcash"] = "Cash",
        ["moneytypbank"] = "Bank",
        ["moneytypblack"] = "Black Money",
        ["vehicletop"] = "VEHICLE",
        ["vehiclenametop"] = "NAME",
        ["vehiclespawntop"] = "SPAWN",
        ["vehiclefliptop"] = "FLIP VEHICLE",
        ["vehiclefulltop"] = "FULLTUNE",
        ["vehiclegodtop"] = "GODMODE",
        ["vehiclereptop"] = "REPAIR",
        ["vehicledeltop"] = "DELETE",
        ["admintop"] = "ADMIN",
        ["adutysada"] = "ON/OFF DUTY",
        ["tpmsada"] = "TP TO MARKER",
        ["tpcsada"] = "TP TO COORDS",
        ["reviveallsada"] = "REVIVE ALL",
        ["delcarsada"] = "DELETE ALL CARS",
        ["delobjsada"] = "DELETE ALL OBJECTS",
        ["delpedssada"] = "DELETE ALL PEDS",
        ["kickallsada"] = "KICK ALL PLAYERS",
        ["cheetostop"] = "ESP",
        ["cheetosesptop"] = "ESP",
        ["cheetosenabletop"] = "Enable",
        ["cheetosnamestop"] = "Names",
        ["cheetosinfotop"] = "Info",
        ["cheetosboxtop"] = "Box",
        ["cheetoslinestop"] = "Lines",
        ["cheetosdebugtop"] = "Debug",
        ["cheetosnocliptop"] = "NOCLIP",
        ["cheetossuicidetop"] = "SUICIDE",
        ["cheetosrevivetop"] = "REVIVE",
        ["cheetosinvisibletop"] = "INVISIBLE",
        ["cheetoshealtop"] = "HEAL",
        ["cheetosarmortop"] = "ARMOUR",
        ["cheetosgodtop"] = "GODMODE",
        ["cheetosallweaponstop"] = "ALL WEAPONS",
        ["cheetosremweatop"] = "DELETE ALL WEAPONS",
        ["giveitem"] = "You gived ",
        ["warn"] = "You got warned by ",
        ["warn2"] = " Reason: ",
        ["warn3"] = "You warned: ",
        ["warn4"] = " Reason: ",
        ["bannedmessage"] = "You are Banned from this server!",
        ["bannedmessage2"] = "You got Banned from this server!",
        ["bannedperma"] = "You are permanently Banned from this server!",
        ["bannedby"] = "Banned by ",
        ["bannedreason"] = "Reason: ",
        ["bannedid"] = "Ban ID: ",
        ["bannedduration"] = "Banned until: ",
        ["bannedinvitetext"] = "For more Information and the Support Join our Discord:",
        ["bannedinvite"] = "discord.gg/dnzscripts",
        ["noreason"] = "You didn't give a reason.",
        ["youbanned"] = "You banned: ",
        ["youbannedreason"] = " Reason: ",
        ["youunbanned"] = "You unbanned Ban ID: ",
        ["noclip"] = "Noclip: Activated",
        ["youkicked"] = "You kicked ",
        ["youkickedreason"] = " Reason: ",
        ["noclip2"] = "Noclip: Deactivated",
        ["notinduty"] = "You are not in Aduty",
        ["notallowed"] = "You are not allowed to do that.",
        ["consoleaccses"] = "Unable to use command, console access required",
        ["lengthnotallowed"] = "You are not allowed to use this length.",
        ["nooneselected"] = "You selected no one.",
        ["gotfreezed"] = "You got un/freezed by ",
        ["screenshotwaiting"] = "Waiting for Screenshot...",
        ["screenshotdone"] = "Screenshot done.",
        ["freezed"] = "You un/freezed ",
        ["revive"] = "You revived ",
        ["gotrevived"] = "You got revived by ",
        ["nomarker"] = "You have no Waypoint.",
        ["noinput"] = "You dont fill out all gabs.",
        ["aduty"] = "You are now in Aduty.",
        ["noaduty"] = "You are not anymore in Aduty.",
        ["vehiclegodmode"] = "Vehicle Godmode enabled.",
        ["notvehiclegodmode"] = "Vehicle Godmode disabled.",
        ["godmode"] = "Godmode enabled.",
        ["notgodmode"] = "Godmode disabled.",
        ["noinputveh"] = "You didnt put in a Spawnname.",
        ["vanish"] = "You are now in vanish",
        ["vanish2"] = "You are not anymore now in vanish",
        ["youdeletedwarn"] = "You deleted warn:",
        ["banlistplaceholder"] = "Search...",
        ["playersearchplaceholder"] = "Search for ID or name...",
        ["reasonplaceholder"] = "Reason for kick, warn, ban",
        ["errorweapon"] = "This weapon doesnt exist.",
    }
}
-- NORMAL ADMINSUITS
-- IF YOU HAVE CUSTOM GROUPS SCROLL DOWN
Config.Suits = {
    male = {
        superadmin = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 139,   ['torso_2'] = 3,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 49,
            ['pants_1'] = 130,   ['pants_2'] = 1,
            ['shoes_1'] = 25,   ['shoes_2'] = 0,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 0,  ['mask_2'] = 2,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 85,  ['bproof_2'] = 0
        },
        admin = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 139,   ['torso_2'] = 3,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 49,
            ['pants_1'] = 130,   ['pants_2'] = 1,
            ['shoes_1'] = 25,   ['shoes_2'] = 0,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 0,  ['mask_2'] = 2,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 85,  ['bproof_2'] = 4
        },
        mod = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 139,   ['torso_2'] = 3,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 49,
            ['pants_1'] = 130,   ['pants_2'] = 1,
            ['shoes_1'] = 25,   ['shoes_2'] = 0,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 0,  ['mask_2'] = 2,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 85,  ['bproof_2'] = 1
        }
    },
    female = {
        superadmin = {
            ['tshirt_1'] = 14,  ['tshirt_2'] = 0,
            ['torso_1'] = 136,   ['torso_2'] = 3,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 49,
            ['pants_1'] = 170,   ['pants_2'] = 0,
            ['shoes_1'] = 144,   ['shoes_2'] = 0,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 0,  ['mask_2'] = 0,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 93,  ['bproof_2'] = 0
        },
        admin = {
            ['tshirt_1'] = 14,  ['tshirt_2'] = 0,
            ['torso_1'] = 136,   ['torso_2'] = 3,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 49,
            ['pants_1'] = 170,   ['pants_2'] = 0,
            ['shoes_1'] = 144,   ['shoes_2'] = 0,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 0,  ['mask_2'] = 0,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 93,  ['bproof_2'] = 1
        },
        mod = {
            ['tshirt_1'] = 14,  ['tshirt_2'] = 0,
            ['torso_1'] = 136,   ['torso_2'] = 3,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 49,
            ['pants_1'] = 170,   ['pants_2'] = 0,
            ['shoes_1'] = 144,   ['shoes_2'] = 0,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 0,  ['mask_2'] = 0,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 93,  ['bproof_2'] = 2
        }
    }
}
-- SPECIAL SUITS FOR SPECIFIC NAMES
-- ONLY THESE 10 YOU CANNOT ADD MORE
-- Maybe will not Work with Custom Groups [NOT TESTET]
Config.specialsuit = {
    Name1 = "Scytek", -- NAME FOR SPECIAL SUIT 1
    Name2 = "",
    Name3 = "",
    Name4 = "",
    Name5 = "",
    Name6 = "",
    Name7 = "",
    Name8 = "",
    Name9 = "",
    Name10 = "",
    Suit1 = { 
        male = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 287,   ['torso_2'] = 12,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 3,
            ['pants_1'] = 114,   ['pants_2'] = 12,
            ['shoes_1'] = 78,   ['shoes_2'] = 12,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 135,  ['mask_2'] = 12,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        },
        female = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 300,   ['torso_2'] = 9,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 8,
            ['pants_1'] = 121,   ['pants_2'] = 9,
            ['shoes_1'] = 82,   ['shoes_2'] = 9,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 153,  ['mask_2'] = 9,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        }
    },
    Suit2 = { 
        male = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 287,   ['torso_2'] = 12,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 3,
            ['pants_1'] = 114,   ['pants_2'] = 12,
            ['shoes_1'] = 78,   ['shoes_2'] = 12,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 135,  ['mask_2'] = 12,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        },
        female = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 300,   ['torso_2'] = 9,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 8,
            ['pants_1'] = 121,   ['pants_2'] = 9,
            ['shoes_1'] = 82,   ['shoes_2'] = 9,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 153,  ['mask_2'] = 9,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        }
    },
    Suit3 = { 
        male = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 287,   ['torso_2'] = 12,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 3,
            ['pants_1'] = 114,   ['pants_2'] = 12,
            ['shoes_1'] = 78,   ['shoes_2'] = 12,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 135,  ['mask_2'] = 12,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        },
        female = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 300,   ['torso_2'] = 9,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 8,
            ['pants_1'] = 121,   ['pants_2'] = 9,
            ['shoes_1'] = 82,   ['shoes_2'] = 9,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 153,  ['mask_2'] = 9,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        }
    },
    Suit4 = { 
        male = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 287,   ['torso_2'] = 12,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 3,
            ['pants_1'] = 114,   ['pants_2'] = 12,
            ['shoes_1'] = 78,   ['shoes_2'] = 12,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 135,  ['mask_2'] = 12,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        },
        female = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 300,   ['torso_2'] = 9,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 8,
            ['pants_1'] = 121,   ['pants_2'] = 9,
            ['shoes_1'] = 82,   ['shoes_2'] = 9,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 153,  ['mask_2'] = 9,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        }
    },
    Suit5 = {
        male = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 287,   ['torso_2'] = 12,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 3,
            ['pants_1'] = 114,   ['pants_2'] = 12,
            ['shoes_1'] = 78,   ['shoes_2'] = 12,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 135,  ['mask_2'] = 12,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        },
        female = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 300,   ['torso_2'] = 9,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 8,
            ['pants_1'] = 121,   ['pants_2'] = 9,
            ['shoes_1'] = 82,   ['shoes_2'] = 9,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 153,  ['mask_2'] = 9,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        }
    },
    Suit6 = {
        male = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 287,   ['torso_2'] = 12,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 3,
            ['pants_1'] = 114,   ['pants_2'] = 12,
            ['shoes_1'] = 78,   ['shoes_2'] = 12,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 135,  ['mask_2'] = 12,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        },
        female = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 300,   ['torso_2'] = 9,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 8,
            ['pants_1'] = 121,   ['pants_2'] = 9,
            ['shoes_1'] = 82,   ['shoes_2'] = 9,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 153,  ['mask_2'] = 9,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        }
    },
    Suit7 = {
        male = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 287,   ['torso_2'] = 12,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 3,
            ['pants_1'] = 114,   ['pants_2'] = 12,
            ['shoes_1'] = 78,   ['shoes_2'] = 12,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 135,  ['mask_2'] = 12,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        },
        female = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 300,   ['torso_2'] = 9,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 8,
            ['pants_1'] = 121,   ['pants_2'] = 9,
            ['shoes_1'] = 82,   ['shoes_2'] = 9,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 153,  ['mask_2'] = 9,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        }
    },
    Suit8 = {
        male = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 287,   ['torso_2'] = 12,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 3,
            ['pants_1'] = 114,   ['pants_2'] = 12,
            ['shoes_1'] = 78,   ['shoes_2'] = 12,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 135,  ['mask_2'] = 12,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        },
        female = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 300,   ['torso_2'] = 9,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 8,
            ['pants_1'] = 121,   ['pants_2'] = 9,
            ['shoes_1'] = 82,   ['shoes_2'] = 9,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 153,  ['mask_2'] = 9,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        }
    },
    Suit9 = {
        male = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 287,   ['torso_2'] = 12,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 3,
            ['pants_1'] = 114,   ['pants_2'] = 12,
            ['shoes_1'] = 78,   ['shoes_2'] = 12,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 135,  ['mask_2'] = 12,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        },
        female = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 300,   ['torso_2'] = 9,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 8,
            ['pants_1'] = 121,   ['pants_2'] = 9,
            ['shoes_1'] = 82,   ['shoes_2'] = 9,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 153,  ['mask_2'] = 9,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        }
    },
    Suit10 = {
        male = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 287,   ['torso_2'] = 12,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 3,
            ['pants_1'] = 114,   ['pants_2'] = 12,
            ['shoes_1'] = 78,   ['shoes_2'] = 12,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 135,  ['mask_2'] = 12,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        },
        female = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 300,   ['torso_2'] = 9,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 8,
            ['pants_1'] = 121,   ['pants_2'] = 9,
            ['shoes_1'] = 82,   ['shoes_2'] = 9,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 153,  ['mask_2'] = 9,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        }
    }
}
-- IF YOU HAVE CUSTOM GROUPS
-- ONLY THESE 10 YOU CANNOT ADD MORE
Config.extragroupsuits = {
    GroupName1 = "",
    GroupName2 = "",
    GroupName3 = "",
    GroupName4 = "",
    GroupName5 = "",
    GroupName6 = "",
    GroupName7 = "",
    GroupName8 = "",
    GroupName9 = "",
    GroupName10 = "",
    Suit1 = {
        male = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 287,   ['torso_2'] = 12,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 3,
            ['pants_1'] = 114,   ['pants_2'] = 12,
            ['shoes_1'] = 78,   ['shoes_2'] = 12,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 135,  ['mask_2'] = 12,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        },
        female = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 300,   ['torso_2'] = 9,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 8,
            ['pants_1'] = 121,   ['pants_2'] = 9,
            ['shoes_1'] = 82,   ['shoes_2'] = 9,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 153,  ['mask_2'] = 9,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        }
    },
    Suit2 = {
        male = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 287,   ['torso_2'] = 12,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 3,
            ['pants_1'] = 114,   ['pants_2'] = 12,
            ['shoes_1'] = 78,   ['shoes_2'] = 12,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 135,  ['mask_2'] = 12,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        },
        female = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 300,   ['torso_2'] = 9,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 8,
            ['pants_1'] = 121,   ['pants_2'] = 9,
            ['shoes_1'] = 82,   ['shoes_2'] = 9,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 153,  ['mask_2'] = 9,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        }
    },
    Suit3 = {
        male = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 287,   ['torso_2'] = 12,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 3,
            ['pants_1'] = 114,   ['pants_2'] = 12,
            ['shoes_1'] = 78,   ['shoes_2'] = 12,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 135,  ['mask_2'] = 12,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        },
        female = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 300,   ['torso_2'] = 9,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 8,
            ['pants_1'] = 121,   ['pants_2'] = 9,
            ['shoes_1'] = 82,   ['shoes_2'] = 9,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 153,  ['mask_2'] = 9,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        }
    },
    Suit4 = {
        male = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 287,   ['torso_2'] = 12,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 3,
            ['pants_1'] = 114,   ['pants_2'] = 12,
            ['shoes_1'] = 78,   ['shoes_2'] = 12,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 135,  ['mask_2'] = 12,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        },
        female = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 300,   ['torso_2'] = 9,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 8,
            ['pants_1'] = 121,   ['pants_2'] = 9,
            ['shoes_1'] = 82,   ['shoes_2'] = 9,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 153,  ['mask_2'] = 9,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        }
    },
    Suit5 = {
        male = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 287,   ['torso_2'] = 12,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 3,
            ['pants_1'] = 114,   ['pants_2'] = 12,
            ['shoes_1'] = 78,   ['shoes_2'] = 12,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 135,  ['mask_2'] = 12,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        },
        female = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 300,   ['torso_2'] = 9,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 8,
            ['pants_1'] = 121,   ['pants_2'] = 9,
            ['shoes_1'] = 82,   ['shoes_2'] = 9,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 153,  ['mask_2'] = 9,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        }
    },
    Suit6 = {
        male = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 287,   ['torso_2'] = 12,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 3,
            ['pants_1'] = 114,   ['pants_2'] = 12,
            ['shoes_1'] = 78,   ['shoes_2'] = 12,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 135,  ['mask_2'] = 12,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        },
        female = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 300,   ['torso_2'] = 9,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 8,
            ['pants_1'] = 121,   ['pants_2'] = 9,
            ['shoes_1'] = 82,   ['shoes_2'] = 9,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 153,  ['mask_2'] = 9,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        }
    },
    Suit7 = {
        male = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 287,   ['torso_2'] = 12,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 3,
            ['pants_1'] = 114,   ['pants_2'] = 12,
            ['shoes_1'] = 78,   ['shoes_2'] = 12,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 135,  ['mask_2'] = 12,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        },
        female = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 300,   ['torso_2'] = 9,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 8,
            ['pants_1'] = 121,   ['pants_2'] = 9,
            ['shoes_1'] = 82,   ['shoes_2'] = 9,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 153,  ['mask_2'] = 9,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        }
    },
    Suit8 = {
        male = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 287,   ['torso_2'] = 12,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 3,
            ['pants_1'] = 114,   ['pants_2'] = 12,
            ['shoes_1'] = 78,   ['shoes_2'] = 12,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 135,  ['mask_2'] = 12,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        },
        female = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 300,   ['torso_2'] = 9,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 8,
            ['pants_1'] = 121,   ['pants_2'] = 9,
            ['shoes_1'] = 82,   ['shoes_2'] = 9,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 153,  ['mask_2'] = 9,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        }
    },
    Suit9 = {
        male = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 287,   ['torso_2'] = 12,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 3,
            ['pants_1'] = 114,   ['pants_2'] = 12,
            ['shoes_1'] = 78,   ['shoes_2'] = 12,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 135,  ['mask_2'] = 12,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        },
        female = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 300,   ['torso_2'] = 9,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 8,
            ['pants_1'] = 121,   ['pants_2'] = 9,
            ['shoes_1'] = 82,   ['shoes_2'] = 9,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 153,  ['mask_2'] = 9,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        }
    },
    Suit10 = {
        male = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 287,   ['torso_2'] = 12,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 3,
            ['pants_1'] = 114,   ['pants_2'] = 12,
            ['shoes_1'] = 78,   ['shoes_2'] = 12,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 135,  ['mask_2'] = 12,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        },
        female = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 300,   ['torso_2'] = 9,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 8,
            ['pants_1'] = 121,   ['pants_2'] = 9,
            ['shoes_1'] = 82,   ['shoes_2'] = 9,
            ['helmet_1'] = -1,  ['helmet_2'] = 0,
            ['mask_1'] = 153,  ['mask_2'] = 9,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['ears_1'] = 0,     ['ears_2'] = 0,
            ['bags_1'] = 0,     ['bags_2'] = 0,
            ['hair_1'] = 0,     ['hair_2'] = 0,
            ['bproof_1'] = 0,  ['bproof_2'] = 0
        }
    }
}