RS.entitiesProtection = true -- Entity/AntiNuke Masterswitch

RS.entitiesOnlyPlayerSpawn = false -- (true > heavier > Detects more precisely blacklisted entities) (false > lighter > Detects only player spawn entities)


--NEW Entity Spawn Lock
-----------------------
--false > disabled
--"inactive" > Users can spawn entities normally
--"relaxed" > NPC and Traffic is allowed, Blocked Client Sided entity spawning
--"strict" > NPC and Traffic are blocked, Blocked Client Sided entity spawning
--WARNING! using this feature will block any kind of Client Sided spawning
--THIS will require spawning entities from the server side
--ADJUST your server resources before continuing.
-----------------------
RS.entities_spawnlock = "inactive"

--Objects/Models
RS.entities_objectsdetection = true -- Detect objects
RS.entities_objectsDetectionMode = 2 -- 0 Warning, 1 Kick, 2 Ban

--Vehicles
RS.entities_vehiclesdetection = true -- Detect Vehicles
RS.entities_vehiclesDetectionMode = 2 -- 0 Warning, 1 Kick, 2 Ban

--Peds
RS.entities_pedsdetection = false -- Detect Peds
RS.entities_pedsDetectionMode = 2 -- 0 Warning, 1 Kick, 2 Ban

RS.entities_blockall = false -- EVERYTHING will be detected except for Whitelisted things...

RS.entities_antinukeProtection = true
RS.entities_antinuke_peds = false
RS.entities_antinuke_vehicles = true
RS.entities_antinuke_objects = false -- UNDER TESTING (GOOD BUT NOT FOR EVERYONE!!)
RS.entities_antinuke_maxspawn = 5 -- After 5 Spawned PEDS/VEH/OBJ the player gets automatically warned
RS.entities_antinuke_resettime = 8000 -- After 8 seconds the AntiNuke timer gets reseted
RS.entities_antinuke_detectionMode = 2 -- 0 Warning, 1 Kick, 2 Ban

RS.entities_whitelisted_objects = { -- You can add here any kind of objects/prop you want to whitelist and don't waste time on checks
    [`prop_cs_ciggy_01`] = { name = "prop_cs_ciggy_01" },
    [`prop_mp_cone_01`] = { name = "prop_mp_cone_01" },
    [`prop_barrier_work05`] = { name = "prop_barrier_work05" },
    [`p_ld_stinger_s`] = { name = "p_ld_stinger_s" },
    [`prop_barier_conc_05b`] = { name = "prop_barier_conc_05b" },
    [`prop_mp_barrier_01b`] = { name = "prop_mp_barrier_01b" },
    [`prop_conc_sacks_02a`] = { name = "prop_conc_sacks_02a" },
    [`prop_mp_arrow_barrier_01`] = { name = "prop_mp_arrow_barrier_01" },
    [`prop_mp_barrier_02b`] = { name = "prop_mp_barrier_02b" },
    [`prop_plas_barier_01a`] = { name = "prop_plas_barier_01a" },
    [`prop_shuttering01`] = { name = "prop_shuttering01" },
    [`prop_worklight_03b`] = { name = "prop_worklight_03b" },
    [`hei_prop_heist_box`] = { name = "hei_prop_heist_box" },
    [`p_michael_backpack_s`] = { name = "p_michael_backpack_s" },
    [`prop_acc_guitar_01`] = { name = "prop_acc_guitar_01" },
    [`prop_amb_beer_bottle`] = { name = "prop_amb_beer_bottle" },
    [`ba_prop_battle_glowstick_01`] = { name = "ba_prop_battle_glowstick_01" },
    [`ba_prop_battle_hobby_horse`] = { name = "ba_prop_battle_hobby_horse" },
    [`hei_heist_sh_bong_01`] = { name = "hei_heist_sh_bong_01" },
}

RS.entities_blacklisted_objects = { -- You can blacklist any prop don't want on the server, and if it's spawned by a player it triggers a detection
    [`prop_fnclink_05crnr1`] = { name = "prop_fnclink_05crnr1" },
    [`xs_prop_hamburgher_wl`] = { name = "xs_prop_hamburgher_wl" },
    [`xs_prop_plastic_bottle_wl`] = { name = "xs_prop_plastic_bottle_wl" },
    [`prop_windmill_01`] = { name = "prop_windmill_01" },
    [`p_spinning_anus_s`] = { name = "p_spinning_anus_s" },
    [`stt_prop_ramp_adj_flip_m`] = { name = "stt_prop_ramp_adj_flip_m" },
    [`stt_prop_ramp_adj_flip_mb`] = { name = "stt_prop_ramp_adj_flip_mb" },
    [`stt_prop_ramp_adj_flip_s`] = { name = "stt_prop_ramp_adj_flip_s" },
    [`stt_prop_ramp_adj_flip_sb`] = { name = "stt_prop_ramp_adj_flip_sb" },
    [`stt_prop_ramp_adj_hloop`] = { name = "stt_prop_ramp_adj_hloop" },
    [`stt_prop_ramp_adj_loop`] = { name = "stt_prop_ramp_adj_loop" },
    [`stt_prop_ramp_jump_l`] = { name = "stt_prop_ramp_jump_l" },
    [`stt_prop_ramp_jump_m`] = { name = "stt_prop_ramp_jump_m" },
    [`stt_prop_ramp_jump_s`] = { name = "stt_prop_ramp_jump_s" },
    [`stt_prop_ramp_jump_xl`] = { name = "stt_prop_ramp_jump_xl" },
    [`stt_prop_ramp_jump_xs`] = { name = "stt_prop_ramp_jump_xs" },
    [`stt_prop_ramp_jump_xxl`] = { name = "stt_prop_ramp_jump_xxl" },
    [`stt_prop_ramp_multi_loop_rb`] = { name = "stt_prop_ramp_multi_loop_rb" },
    [`stt_prop_ramp_spiral_l`] = { name = "stt_prop_ramp_spiral_l" },
    [`stt_prop_ramp_spiral_l_l`] = { name = "stt_prop_ramp_spiral_l_l" },
    [`stt_prop_ramp_spiral_l_m`] = { name = "stt_prop_ramp_spiral_l_m" },
    [`stt_prop_ramp_spiral_l_s`] = { name = "stt_prop_ramp_spiral_l_s" },
    [`stt_prop_ramp_spiral_l_xxl`] = { name = "stt_prop_ramp_spiral_l_xxl" },
    [`stt_prop_ramp_spiral_m`] = { name = "stt_prop_ramp_spiral_m" },
    [`stt_prop_ramp_spiral_s`] = { name = "stt_prop_ramp_spiral_s" },
    [`stt_prop_ramp_spiral_xxl`] = { name = "stt_prop_ramp_spiral_xxl" },
    [`stt_prop_stunt_track_dwuturn`] = { name = "stt_prop_stunt_track_dwuturn" },
    [`stt_prop_stunt_track_dwslope30`] = { name = "stt_prop_stunt_track_dwslope30" },
    [`stt_prop_stunt_track_start`] = { name = "stt_prop_stunt_track_start" },
    [`stt_prop_stunt_track_hill2`] = { name = "stt_prop_stunt_track_hill2" },
    [`stt_prop_stunt_bblock_huge_01`] = { name = "stt_prop_stunt_bblock_huge_01" },
    [`stt_prop_stunt_bblock_huge_02`] = { name = "stt_prop_stunt_bblock_huge_02" },
    [`stt_prop_stunt_bblock_huge_03`] = { name = "stt_prop_stunt_bblock_huge_03" },
    [`stt_prop_stunt_bblock_huge_04`] = { name = "stt_prop_stunt_bblock_huge_04" },
    [`stt_prop_stunt_bblock_huge_05`] = { name = "stt_prop_stunt_bblock_huge_05" },
    [`stt_prop_stunt_bblock_hump_01`] = { name = "stt_prop_stunt_bblock_hump_01" },
    [`stt_prop_stunt_bblock_hump_02`] = { name = "stt_prop_stunt_bblock_hump_02" },
    [`stt_prop_stunt_bblock_lrg1`] = { name = "stt_prop_stunt_bblock_lrg1" },
    [`stt_prop_stunt_bblock_lrg2`] = { name = "stt_prop_stunt_bblock_lrg2" },
    [`stt_prop_stunt_bblock_lrg3`] = { name = "stt_prop_stunt_bblock_lrg3" },
    [`stt_prop_stunt_bblock_mdm1`] = { name = "stt_prop_stunt_bblock_mdm1" },
    [`stt_prop_stunt_bblock_mdm2`] = { name = "stt_prop_stunt_bblock_mdm2" },
    [`stt_prop_stunt_bblock_mdm3`] = { name = "stt_prop_stunt_bblock_mdm3" },
    [`stt_prop_stunt_bblock_qp`] = { name = "stt_prop_stunt_bblock_qp" },
    [`stt_prop_stunt_bblock_qp2`] = { name = "stt_prop_stunt_bblock_qp2" },
    [`stt_prop_stunt_bblock_qp3`] = { name = "stt_prop_stunt_bblock_qp3" },
    [`prop_beach_fire`] = { name = "prop_beach_fire" },
    [`prop_gas_pump_1a`] = { name = "prop_gas_pump_1a" },
    [`prop_gas_pump_1b`] = { name = "prop_gas_pump_1b" },
    [`prop_gas_pump_1c`] = { name = "prop_gas_pump_1c" },
    [`prop_gas_pump_1d`] = { name = "prop_gas_pump_1d" },
    [`prop_gas_pump_old2`] = { name = "prop_gas_pump_old2" },
    [`prop_gas_pump_old3`] = { name = "prop_gas_pump_old3" },
    [`prop_vintage_pump`] = { name = "prop_vintage_pump" },
    [`apa_mp_h_acc_box_trinket_01`] = { name = "apa_mp_h_acc_box_trinket_01" },
    [`prop_roundbailer02`] = { name = "prop_roundbailer02" },
    [`prop_roundbailer01`] = { name = "prop_roundbailer01" },
    [`prop_container_05a`] = { name = "prop_container_05a" },
    [`stt_prop_stunt_bowling_ball`] = { name = "stt_prop_stunt_bowling_ball" },
    [`apa_mp_h_acc_rugwoolm_03`] = { name = "apa_mp_h_acc_rugwoolm_03" },
    [`prop_container_ld2`] = { name = "prop_container_ld2" },
    [`hei_prop_carrier_cargo_02a`] = { name = "hei_prop_carrier_cargo_02a" },
    [`p_cablecar_s`] = { name = "p_cablecar_s" },
    [`p_ferris_car_01`] = { name = "p_ferris_car_01" },
    [`prop_cj_big_boat`] = { name = "prop_cj_big_boat" },
    [`prop_rock_4_big2`] = { name = "prop_rock_4_big2" },
    [`prop_steps_big_01`] = { name = "prop_steps_big_01" },
    [`v_ilev_lest_bigscreen`] = { name = "v_ilev_lest_bigscreen" },
    [`prop_carcreeper`] = { name = "prop_carcreeper" },
    [`apa_mp_h_bed_double_09`] = { name = "apa_mp_h_bed_double_09" },
    [`apa_mp_h_bed_wide_05`] = { name = "apa_mp_h_bed_wide_05" },
    [`prop_cattlecrush`] = { name = "prop_cattlecrush" },
    [`prop_cs_documents_01`] = { name = "prop_cs_documents_01" },
    [`prop_ferris_car_01_lod1`] = { name = "prop_ferris_car_01_lod1" },
    [`prop_construcionlamp_01`] = { name = "prop_construcionlamp_01" },
    [`prop_fncconstruc_01d`] = { name = "prop_fncconstruc_01d" },
    [`prop_fncconstruc_02a`] = { name = "prop_fncconstruc_02a" },
    [`p_dock_crane_cabl_s`] = { name = "p_dock_crane_cabl_s" },
    [`prop_dock_crane_01`] = { name = "prop_dock_crane_01" },
    [`prop_dock_crane_02_cab`] = { name = "prop_dock_crane_02_cab" },
    [`prop_dock_float_1`] = { name = "prop_dock_float_1" },
    [`prop_dock_crane_lift`] = { name = "prop_dock_crane_lift" },
    [`apa_mp_h_bed_double_08`] = { name = "apa_mp_h_bed_double_08" },
    [`csx_seabed_bldr4_`] = { name = "csx_seabed_bldr4_" },
    [`imp_prop_impexp_sofabed_01a`] = { name = "imp_prop_impexp_sofabed_01a" },
    [`apa_mp_h_yacht_bed_01`] = { name = "apa_mp_h_yacht_bed_01" },
    [`xs_propintxmas_tree_2018`] = { name = "xs_propintxmas_tree_2018" },
    [`xm_prop_x17_xmas_tree_int`] = { name = "xm_prop_x17_xmas_tree_int" },
    [-685641702] = { name = "unknown" },
    [-1230672010] = { name = "unknown" },
    [-1404869155] = { name = "FIB Building" },
    [-759902142] = { name = "prop_fnclink_03a" },
    [`hw1_lod_08_09_16_17_18`] = { name = "hw1_lod_08_09_16_17_18" },
    [`cs4_lod_01_slod3`] = { name = "cs4_lod_01_slod3" },
    [`dt1_21_slod`] = { name = "dt1_21_slod" },
    [`dt1_11_dt1_tower_lod`] = { name = "dt1_11_dt1_tower_lod" },
    [`id2_lod_00_ab_slod2`] = { name = "id2_lod_00_ab_slod2" },
    [`dt1_lod_03_04_05_11`] = { name = "dt1_lod_03_04_05_11" },
    [`kt1_lod_slod4`] = { name = "kt1_lod_slod4" },
    [`ch2_lod3_slod3`] = { name = "ch2_lod3_slod3" },
    [`vb_lod_slod4`] = { name = "vb_lod_slod4" },
}

RS.entities_whitelisted_vehicles = {} -- You can add here any kind of vehicle you want to whitelist and don't waste time on checks
   
RS.entities_blacklisted_vehicles = {
    -- [`cargoplane`] = {name = "Cargo Plane"},
    -- [`dump`] = {name = "Dump"},
    -- [`avenger`] = {name = "Avenger"},
    -- [`avenger2`] = {name = "Avenger2"},
    -- [`luxor`] = {name = "Luxor"},
    -- [`khanjali`] = {name = "Khanjali"},
    -- [`rhino`] = {name = "Rhino"},
    -- [`tampa3`] = {name = "tampa3"},
    -- [`insurgent`] = {name = "Insurgent"},
    -- [`insurgent3`] = {name = "Insurgent3"},
    -- [`oppressor`] = {name = "Oprresor"},
    -- [`oppressor2`] = {name = "Oprresor2"},
    -- [`maverick`] = {name = "Maverick"},
    -- [`blimp2`] = {name = "blimp2"},
    -- [`blimp`] = {name = "blimp"},
    -- [`blimp3`] = {name = "blimp3"},
    -- [`freight`] = {name = "Freight"},
    -- [`freightcar`] = {name = "FreightCar"},
    -- [`limo2`] = {name = "Limo2"},
    -- [`freightcont1`] = {name = "FreightCont1"},
    -- [`freightcont2`] = {name = "FreightCont2"},
    -- [`freightgrain`] = {name = "FreightGrain"},
    -- [`cerberus3`] = {name = "Cerberus3"},
    -- [`cerberus2`] = {name = "Cerberus2"},
    -- [`cerberus`] = {name = "Cerberus"},
    -- [`buzzard`] = {name = "Buzzard"},
    -- [`phantom2`] = {name = "Phantom2"},
    -- [`issi6`] = {name = "Issi6"},
    -- [`issi4`] = {name = "Issi4"},
    -- [`issi5`] = {name = "Issi5"},
    -- [`savage`] = {name = "Savage"},
    -- [`hunter`] = {name = "Hunter"},
    -- [`akula`] = {name = "Akula"},
    -- [`annihilator`] = {name = "Annihilator"},
    -- [`cutter`] = {name = "Cutter"},
    -- [`bulldozer`] = {name = "Bulldozer"},
    -- [`barracks`] = {name = "Barracks"},
    -- [`barracks2`] = {name = "Barracks2"},
    -- [`barracks3`] = {name = "Barracks3"},
    -- [`barrage`] = {name = "Barrage"},
    -- [`chernobog`] = {name = "Chernobog"},
    -- [`crusader`] = {name = "Crusader"},
    -- [`halftrack`] = {name = "HalfTrack"},
    -- [`minitank`] = {name = "MiniTank"},
    -- [`scarab`] = {name = "Scarab"},
    -- [`scarab2`] = {name = "Scarab2"},
    -- [`scarab3`] = {name = "Scarab3"},
    -- [`thruster`] = {name = "Thruster"},
    -- [`trailersmall2`] = {name = "Trailersmall2"},
    -- [`brutus3`] = {name = "Brutus3"},
    -- [`freecrawler`] = {name = "Freecrawler"},
    -- [`monster`] = {name = "Monster"},
    -- [`monster3`] = {name = "Monster3"},
    -- [`monster4`] = {name = "Monster4"},
    -- [`monster5`] = {name = "Monster5"},
    -- [`technical`] = {name = "Technical"},
    -- [`technical3`] = {name = "Technical3"},
    -- [`technical2`] = {name = "Technical2"},
    -- [`nightshark`] = {name = "Nightshark"},
    -- [`zhaba`] = {name = "Zhaba"},
    -- [`formula`] = {name = "Formula"},
    -- [`formula2`] = {name = "Formula2"},
    -- [`scramjet`] = {name = "Scramjet"},
    -- [`zr380`] = {name = "Zr380"},
    -- [`zr3802`] = {name = "Zr3802"},
    -- [`zr3803`] = {name = "Zr3803"},
    -- [`raptor`] = {name = "Raptor"},
    -- [`volatol`] = {name = "Volatol"},
    -- [`voltic2`] = {name = "Voltic2"},
    -- [`tula`] = {name = "Tula"},
    -- [`strikeforce`] = {name = "Strikeforce"},
    -- [`lazer`] = {name = "Lazer"},
    -- [`valkyrie2`] = {name = "Valkyrie2"},
    -- [`valkyrie`] = {name = "Valkyrie"},
    -- [`jet`] = {name = "Jet"},
    -- [`hydra`] = {name = "Hydra"},
    -- [`bombushka`] = {name = "Bombushka"},
    -- [`bruiser3`] = {name = "Bruiser3"},
    -- [`bruiser2`] = {name = "Bruiser2"},
    -- [`bruiser`] = {name = "Bruiser"},
    -- [`caracara`] = {name = "Caracara"},
    -- [`dune5`] = {name = "Dune5"},
    -- [`dune4`] = {name = "Dune4"},
    -- [`dune3`] = {name = "Dune3"},
    -- [`dune2`] = {name = "Dune2"},
    -- [`dune`] = {name = "Dune"},
    -- [`openwheel1`] = {name = "Openwheel1"},
    -- [`paragon2`] = {name = "Paragon2"},
    -- [`blazer5`] = {name = "Blazer5"},
    -- [`slamvan4`] = {name = "Slamvan4"},
    -- [`slamvan5`] = {name = "Slamvan5"},
    -- [`slamvan6`] = {name = "Slamvan6"},
    -- [`adder`] = {name = "Adder"},
    -- [`ruiner2`] = {name = "Ruiner2"},
    -- [`dukes2`] = {name = "Dukes2"},
    -- [`dominator4`] = {name = "Dominator4"},
    -- [`dominator5`] = {name = "Dominator5"},
    -- [`dominator6`] = {name = "Dominator6"},
    -- [`handler`] = {name = "Handler"},
    -- [`vindicator`] = {name = "Vindicator"},
    -- [`wastelander`] = {name = "Wastelander"},
    -- [`ardent`] = {name = "Ardent"},
    -- [`vigilante`] = {name = "Vigilante"},
    -- [`cargobob`] = {name = "Cargobob"},
    -- [`deluxo`] = {name = "Deluxo"},
    -- [`tug`] = {name = "Tug"},
    -- [`menacer`] = {name = "Menacer"},
    -- [`cablecar`] = {name = "Cablecar"},
    -- [`schafter5`] = {name = "Schafter5"},
    -- [`schafter6`] = {name = "Schafter6"},
    -- [`baller5`] = {name = "Baller5"},
    -- [`baller6`] = {name = "Baller6"},
    -- [`kuruma2`] = {name = "Kuruma2"},
    -- [`kuruma`] = {name = "Kuruma"},
    -- [`apc`] = {name = "APC"},
    -- [`airjet`] = {name = "Airjet"},
    -- [`starling`] = {name = "Starling"},
    -- [`squaddie`] = {name = "Squaddie"},
    -- [`asea2`] = {name = "Asea2"},
    -- [`molotok`] = {name = "Molotok"},
    -- [`mogul`] = {name = "Mogul"},
    -- [`pyro`] = {name = "Pyro"},
    -- [`rogue`] = {name = "Rogue"},
    -- [`xls2`] = {name = "Xls2"},
    -- [`dinghy5`] = {name = "Dinghy5"},
    -- [`dinghy`] = {name = "Dinghy"},
    -- [`trash`] = {name = "Trash"},
    -- [`hauler`] = {name = "Hauler"},
    -- [`seasparrow2`] = {name = "Seasparrow2"},
    -- [`seasparrow3`] = {name = "Seasparrow3"},
    -- [`terbyte`] = {name = "Terorbyte"},
    -- [`impaler2`] = {name = "Impaler2"},
    -- [`impaler3`] = {name = "Impaler3"},
    -- [`impaler4`] = {name = "Impaler4"},
    -- [`stockade3`] = {name = "Stockade3"},
    -- [`deathbike`] = {name = "Deathbike"},
    -- [`deathbike2`] = {name = "Deathbike2"},
    -- [`deathbike3`] = {name = "Deathbike3"},
    -- [`velum`] = {name = "Velum"},
    -- [`velum2`] = {name = "Velum2"},
    -- [`coach`] = {name = "Coach"},
    -- [`veto`] = {name = "Veto"},
    -- [`veto2`] = {name = "Veto2"},
    -- [`utillitruck`] = {name = "Utillitruck"},
    -- [`utillitruck2`] = {name = "Utillitruck2"},
    -- [`boxville`] = {name = "Boxville"},
    -- [`boxville2`] = {name = "Boxville2"},
    -- [`boxville3`] = {name = "Boxville3"},
    -- [`boxville5`] = {name = "Boxville5"},
    -- [`boxville4`] = {name = "Boxville4"},
    -- [`youga`] = {name = "Youga"},
    -- [`youga3`] = {name = "Youga3"},
    -- [`forklift`] = {name = "Forklift"},
    -- [`ripley`] = {name = "Ripley"},
    -- [`sadler2`] = {name = "Sadler2"},
    -- [`titan2`] = {name = "Titan2"},
    -- [`imperator`] = {name = "Imperator"},
    -- [`imperator2`] = {name = "Imperator2"},
    -- [`imperator3`] = {name = "Imperator3"},
    -- [`submersible2`] = {name = "Submersible2"},
    -- [`rumpo3`] = {name = "Rumpo3"},
    -- [`avisa`] = {name = "Avisa"},
    -- [`kosatka`] = {name = "Kosatka"},
    -- [`patrolboat`] = {name = "Patrolboat"},
    -- [`hauler2`] = {name = "Hauler2"},
    -- [`skylift`] = {name = "Skylift"},
    -- [`shotaro`] = {name = "Shotaro"},
    -- [`brutus`] = {name = "Imperator2"},
    -- [`brutus2`] = {name = "Brutus2"},
    -- [`toreador`] = {name = "Toreador"},
    -- [`baletrailer`] = {name = "baletrailer"},
    -- [`boattrailer`] = {name = "boattrailer"},
    -- [`graintrailer`] = {name = "graintrailer"},
    -- [`proptrailer`] = {name = "proptrailer"},
    -- [`raketrailer`] = {name = "raketrailer"},
    -- [`tr3`] = {name = "tr3"},
    -- [`trflat`] = {name = "trflat"},
    -- [`trailerlarge`] = {name = "trailerlarge"},
    -- [`trailersmall`] = {name = "trailersmall"},
    -- [`metrotrain`] = {name = "metrotrain"},
    -- [`tankercar`] = {name = "tankercar"},
    -- [`airtug`] = {name = "airtug"},
    -- [`caddy`] = {name = "caddy"},
    -- [`caddy2`] = {name = "caddy2"},
    -- [`caddy3`] = {name = "caddy3"},
    -- [`docktug`] = {name = "docktug"},
    -- [`tractor`] = {name = "tractor"},
    -- [`tractor2`] = {name = "tractor2"},
    -- [`tractor3`] = {name = "tractor3"},
    -- [`slamtruck`] = {name = "slamtruck"},
    -- [`airbus`] = {name = "airbus"},
    -- [`brickade`] = {name = "brickade"},
    -- [`bus`] = {name = "bus"},
    -- [`rallytruck`] = {name = "rallytruck"},
    -- [`mesa2`] = {name = "mesa2"},
    -- [`alkonost`] = {name = "alkonost"},
    -- [`openwheel2`] = {name = "openwheel2"},
    -- [`winky`] = {name = "winky"},
    -- [`verus`] = {name = "verus"},
    -- [`rcbandito`] = {name = "rcbandito"},
    -- [`dloader`] = {name = "dloader"},
    -- [`champion`] = {name = "champion"},
    -- [`cinquemila`] = {name = "cinquemila"},
    -- [`buffalo4`] = {name = "buffalo4"},
    -- [`deity`] = {name = "deity"},
    -- [`ignus`] = {name = "ignus"},
    -- [`jubilee`] = {name = "jubilee"},
    -- [`patriot3`] = {name = "patriot3"},
    -- [`granger2`] = {name = "granger2"},
    -- [`youga4`] = {name = "youga4"},
    -- [`tanker`] = {name = "tanker"},
    -- [`trailerlogs`] = {name = "trailerlogs"},
    -- [`tanker2`] = {name = "tanker2"},
    -- [`tr4`] = {name = "tr4"},
    -- [`tr2`] = {name = "tr2"},
    -- [`armytanker`] = {name = "armytanker"},
    -- [`armytrailer`] = {name = "armytrailer"},
    -- [`armytrailer2`] = {name = "armytrailer2"},
    -- [`docktrailer`] = {name = "docktrailer"},
    -- [`freighttrailer`] = {name = "freighttrailer"},
    -- [`stockade`] = {name = "Stockade"},
}

RS.entities_whitelisted_peds = {
    [`mp_f_freemode_01`] = {name = "Female Ped"},
    [`mp_m_freemode_01`] = {name = "Male Ped"}, 
}

RS.entities_blacklisted_peds = {
    [`a_m_y_mexthug_01`] = {name = "MexThug"},
    -- [`a_c_husky`] = {name = "Huskey"}, 
    [`a_c_boar`] = {name = "Boar"}, 
    [`a_c_sharkhammer`] = {name = "Sharkhammer"}, 
    [`a_c_chimp`] = {name = "Chimp"}, 
    [`a_c_chop`] = {name = "Chop"}, 
    -- [`a_c_hen`] = {name = "Hen"}, 
    [`a_c_humpback`] = {name = "Humpback"}, 
    [`a_c_killerwhale`] = {name = "Killerwhale"},
    [`a_c_rhesus`] = {name = "Rhesus"}, 
    -- [`a_c_rottweiler`] = {name = "Rottweiler"}, 
    [`a_c_sharktiger`] = {name = "SharkTiger"}, 
    -- [`a_c_shepherd`] = {name = "Shepherd"}, 
    [`u_m_y_zombie_01`] = {name = "Zombie"},
    [`a_m_m_acult_01`] = {name = "Acult01"},
    [`u_m_y_juggernaut_01`] = {name = "Juggernaut"},
    [`s_f_y_bartender_01`] = {name = "s_f_y_bartender_01"}, 
    [`a_m_y_beachvesp_01`] = {name = "a_m_y_beachvesp_01"}, 
    [`a_m_y_beach_03`] = {name = "a_m_y_beach_03"}, 
    [`a_m_y_beach_02`] = {name = "a_m_y_beach_02"}, 
    [`a_m_m_beach_02`] = {name = "a_m_m_beach_02"}, 
    [`a_m_y_beach_01`] = {name = "a_m_y_beach_01"}, 
    [`s_m_y_baywatch_01`] = {name = "s_m_y_baywatch_01"}, 
    [`mp_f_boatstaff_01`] = {name = "mp_f_boatstaff_01"}, 
    [`u_m_m_bikehire_01`] = {name = "u_m_m_bikehire_01"}, 
    [`a_f_y_bevhills_04`] = {name = "a_f_y_bevhills_04"}, 
    [`s_m_m_bouncer_01`] = {name = "s_m_m_bouncer_01"}, 
    [`s_m_y_armymech_01`] = {name = "s_m_y_armymech_01"}, 
    [`s_m_y_autopsy_01`] = {name = "s_m_y_autopsy_01"}, 
    [`s_m_y_blackops_01`] = {name = "s_m_y_blackops_01"}, 
    [`s_m_y_blackops_02`] = {name = "s_m_y_blackops_02"},
}