-- [[ Explosion Detection ]]

RS.explosionProtection = true -- Enable/Disable detection for Blacklisted Explosions based on the table below
RS.explosions_maxExplosions = 3 -- Ban the player after 3 explosions
RS.explosions_resetTime = 5000 -- Reset the timer after 5 seconds

RS.explosions_preventExplosions = false -- If enabled all explosions will be cancelled if possible

RS.explosions_BlacklistedExplosionsTable = {
    [1] = { name = "EXP_TAG_GRENADE", detect = true},
    [2] = { name = "EXP_TAG_GRENADELAUNCHER", detect = true},
    [3] = { name = "EXP_TAG_STICKYBOMB", detect = true},
    [4] = { name = "EXP_TAG_MOLOTOV", detect = true},
    [5] = { name = "EXP_TAG_ROCKET", detect = true},
    [6] = { name = "EXP_TAG_TANKSHELL", detect = true},
    [7] = { name = "EXP_TAG_HI_OCTANE", detect = true},
    [8] = { name = "EXP_TAG_CAR", detect = false},
    [9] = { name = "EXP_TAG_PLANE", detect = false},
    [10] = { name = "EXP_TAG_PETROL_PUMP", detect = false},
    [11] = { name = "EXP_TAG_BIKE", detect = false},
    [12] = { name = "EXP_TAG_DIR_STEAM", detect = true},
    [13] = { name = "EXP_TAG_DIR_FLAME", detect = true},
    [14] = { name = "EXP_TAG_DIR_WATER_HYDRANT", detect = false},
    [15] = { name = "EXP_TAG_DIR_GAS_CANISTER", detect = false},
    [16] = { name = "EXP_TAG_BOAT", detect = true},
    [17] = { name = "EXP_TAG_SHIP_DESTROY", detect = true},
    [18] = { name = "EXP_TAG_TRUCK", detect = false},
    [19] = { name = "EXP_TAG_BULLET", detect = true},
    [20] = { name = "EXP_TAG_SMOKEGRENADELAUNCHER", detect = true},
    [21] = { name = "EXP_TAG_SMOKEGRENADE", detect = true},
    [22] = { name = "EXP_TAG_BZGAS", detect = true},
    [23] = { name = "EXP_TAG_FLARE", detect = true},
    [24] = { name = "EXP_TAG_GAS_CANISTER", detect = false},
    [25] = { name = "EXP_TAG_EXTINGUISHER", detect = true},
    [26] = { name = "EXP_TAG_PROGRAMMABLEAR", detect = true},
    [27] = { name = "EXP_TAG_TRAIN", detect = true},
    [28] = { name = "EXP_TAG_BARREL", detect = true},
    [29] = { name = "EXP_TAG_PROPANE", detect = true},
    [30] = { name = "EXP_TAG_BLIMP", detect = true},
    [31] = { name = "EXP_TAG_DIR_FLAME_EXPLODE", detect = true},
    [32] = { name = "EXP_TAG_TANKER", detect = true},
    [33] = { name = "EXP_TAG_PLANE_ROCKET", detect = true},
    [34] = { name = "EXP_TAG_VEHICLE_BULLET", detect = true},
    [35] = { name = "EXP_TAG_GAS_TANK", detect = true},
    [36] = { name = "EXP_TAG_BIRD_CRAP", detect = true},
    [37] = { name = "EXP_TAG_RAILGUN", detect = true},
    [38] = { name = "EXP_TAG_BLIMP", detect = true},
    [39] = { name = "EXP_TAG_FIREWORK", detect = true},
    [40] = { name = "EXP_TAG_SNOWBALL", detect = true},
    [41] = { name = "EXP_TAG_PROXMINE", detect = true},
    [42] = { name = "EXP_TAG_VALKYRIE_CANNON", detect = true},
    [43] = { name = "EXP_TAG_AIR_DEFENSE", detect = true},
    [44] = { name = "EXP_TAG_PIPEBOMB", detect = true},
    [45] = { name = "EXP_TAG_VEHICLEMINE", detect = true},
    [46] = { name = "EXP_TAG_EXPLOSIVEAMMO", detect = true},
    [47] = { name = "EXP_TAG_APCSHELL", detect = true},
    [48] = { name = "EXP_TAG_BOMB_CLUSTER", detect = true},
    [49] = { name = "EXP_TAG_BOMB_GAS", detect = true},
    [50] = { name = "EXP_TAG_BOMB_INCENDIARY", detect = true},
    [51] = { name = "EXP_TAG_BOMB_STANDARD", detect = true},
    [52] = { name = "EXP_TAG_TORPEDO", detect = true},
    [53] = { name = "EXP_TAG_TORPEDO_UNDERWATER", detect = true},
    [54] = { name = "EXP_TAG_BOMBUSHKA_CANNON", detect = true},
    [55] = { name = "EXP_TAG_BOMB_CLUSTER_SECONDARY", detect = true},
    [56] = { name = "EXP_TAG_HUNTER_BARRAGE", detect = true},
    [57] = { name = "EXP_TAG_HUNTER_CANNON", detect = true},
    [58] = { name = "EXP_TAG_ROGUE_CANNON", detect = true},
    [59] = { name = "EXP_TAG_MINE_UNDERWATER", detect = true},
    [60] = { name = "EXP_TAG_ORBITAL_CANNON", detect = true},
    [61] = { name = "EXP_TAG_BOMB_STANDARD_WIDE", detect = true},
    [62] = { name = "EXP_TAG_EXPLOSIVEAMMO_SHOTGUN", detect = true},
    [63] = { name = "EXP_TAG_OPPRESSOR_CANNON", detect = true},
    [64] = { name = "EXP_TAG_MORTAR_KINETIC", detect = true},
    [65] = { name = "EXP_TAG_VEHICLEMINE_KINETIC", detect = true},
    [66] = { name = "EXP_TAG_VEHICLEMINE_EMP", detect = true},
    [67] = { name = "EXP_TAG_VEHICLEMINE_SPIKE", detect = true},
    [68] = { name = "EXP_TAG_VEHICLEMINE_SLICK", detect = true},
    [69] = { name = "EXP_TAG_VEHICLEMINE_TAR", detect = true},
    [70] = { name = "EXP_TAG_SCRIPT_DRONE", detect = true},
    [71] = { name = "EXP_TAG_RAYGUN", detect = true},
    [72] = { name = "EXP_TAG_BURIEDMINE", detect = true},
    [73] = { name = "EXP_TAG_SCRIPT_MISSILE", detect = true}
}