local function UnloadIpl()
	RemoveIpl('int_hotel_corridor01')
	RemoveIpl('int_hotel_doubleroom101')
	RemoveIpl('int_hotel_doubleroom102')
	RemoveIpl('int_hotel_doubleroom103')
	RemoveIpl('int_hotel_doubleroom104')
	RemoveIpl('int_hotel_doubleroom105')
	RemoveIpl('int_hotel_doubleroom106')
	RemoveIpl('int_hotel_room101')
	RemoveIpl('int_hotel_room102')
	RemoveIpl('int_hotel_room103')
	RemoveIpl('int_hotel_room104')
	RemoveIpl('int_hotel_room105')
	RemoveIpl('int_hotel_room106')
	RemoveIpl('int_hotel_room107')
	RemoveIpl('int_hotel_room108')
	RemoveIpl('int_hotel_room109')
	RemoveIpl('int_hotel_room110')
	RemoveIpl('int_hotel_room111')
	RemoveIpl('int_hotel_room112')
	RemoveIpl('int_hotel_room113')
	RemoveIpl('int_hotel_room114')
	RemoveIpl('int_hotel_room115')
	RemoveIpl('int_hotel_room116')
	RemoveIpl('int_hotel_room117')
	RemoveIpl('int_hotel_room118')
	RemoveIpl('int_hotel_room119')
	RemoveIpl('int_hotel_room120')
	RemoveIpl('int_hotel_room121')
	RemoveIpl('int_hotel_room122')
	RemoveIpl('int_hotel_room123')
	RemoveIpl('int_hotel_room124')

	RemoveIpl('int_hotel_corridor02')
	RemoveIpl('int_hotel_doubleroom201')
	RemoveIpl('int_hotel_doubleroom202')
	RemoveIpl('int_hotel_doubleroom203')
	RemoveIpl('int_hotel_doubleroom204')
	RemoveIpl('int_hotel_doubleroom205')
	RemoveIpl('int_hotel_doubleroom206')
	RemoveIpl('int_hotel_room201')
	RemoveIpl('int_hotel_room202')
	RemoveIpl('int_hotel_room203')
	RemoveIpl('int_hotel_room204')
	RemoveIpl('int_hotel_room205')
	RemoveIpl('int_hotel_room206')
	RemoveIpl('int_hotel_room207')
	RemoveIpl('int_hotel_room208')
	RemoveIpl('int_hotel_room209')
	RemoveIpl('int_hotel_room210')
	RemoveIpl('int_hotel_room211')
	RemoveIpl('int_hotel_room212')
	RemoveIpl('int_hotel_room213')
	RemoveIpl('int_hotel_room214')
	RemoveIpl('int_hotel_room215')
	RemoveIpl('int_hotel_room216')
	RemoveIpl('int_hotel_room217')
	RemoveIpl('int_hotel_room218')
	RemoveIpl('int_hotel_room219')
	RemoveIpl('int_hotel_room220')
	RemoveIpl('int_hotel_room221')
	RemoveIpl('int_hotel_room222')
	RemoveIpl('int_hotel_room223')
	RemoveIpl('int_hotel_room224')

	RemoveIpl('int_hotel_corridor03')
	RemoveIpl('int_hotel_doubleroom301')
	RemoveIpl('int_hotel_doubleroom302')
	RemoveIpl('int_hotel_doubleroom303')
	RemoveIpl('int_hotel_doubleroom304')
	RemoveIpl('int_hotel_doubleroom305')
	RemoveIpl('int_hotel_doubleroom306')
	RemoveIpl('int_hotel_room301')
	RemoveIpl('int_hotel_room302')
	RemoveIpl('int_hotel_room303')
	RemoveIpl('int_hotel_room304')
	RemoveIpl('int_hotel_room305')
	RemoveIpl('int_hotel_room306')
	RemoveIpl('int_hotel_room307')
	RemoveIpl('int_hotel_room308')
	RemoveIpl('int_hotel_room309')
	RemoveIpl('int_hotel_room310')
	RemoveIpl('int_hotel_room311')
	RemoveIpl('int_hotel_room312')
	RemoveIpl('int_hotel_room313')
	RemoveIpl('int_hotel_room314')
	RemoveIpl('int_hotel_room315')
	RemoveIpl('int_hotel_room316')
	RemoveIpl('int_hotel_room317')
	RemoveIpl('int_hotel_room318')
	RemoveIpl('int_hotel_room319')
	RemoveIpl('int_hotel_room320')
	RemoveIpl('int_hotel_room321')
	RemoveIpl('int_hotel_room322')
	RemoveIpl('int_hotel_room323')
	RemoveIpl('int_hotel_room324')

	RemoveIpl('int_hotel_corridor04')
	RemoveIpl('int_hotel_doubleroom401')
	RemoveIpl('int_hotel_doubleroom402')
	RemoveIpl('int_hotel_doubleroom403')
	RemoveIpl('int_hotel_doubleroom404')
	RemoveIpl('int_hotel_doubleroom405')
	RemoveIpl('int_hotel_doubleroom406')
	RemoveIpl('int_hotel_room401')
	RemoveIpl('int_hotel_room402')
	RemoveIpl('int_hotel_room403')
	RemoveIpl('int_hotel_room404')
	RemoveIpl('int_hotel_room405')
	RemoveIpl('int_hotel_room406')
	RemoveIpl('int_hotel_room407')
	RemoveIpl('int_hotel_room408')
	RemoveIpl('int_hotel_room409')
	RemoveIpl('int_hotel_room410')
	RemoveIpl('int_hotel_room411')
	RemoveIpl('int_hotel_room412')
	RemoveIpl('int_hotel_room413')
	RemoveIpl('int_hotel_room414')
	RemoveIpl('int_hotel_room415')
	RemoveIpl('int_hotel_room416')
	RemoveIpl('int_hotel_room417')
	RemoveIpl('int_hotel_room418')
	RemoveIpl('int_hotel_room419')
	RemoveIpl('int_hotel_room420')
	RemoveIpl('int_hotel_room421')
	RemoveIpl('int_hotel_room422')
	RemoveIpl('int_hotel_room423')
	RemoveIpl('int_hotel_room424')

	RemoveIpl('int_hotel_corridor05')
	RemoveIpl('int_hotel_doubleroom501')
	RemoveIpl('int_hotel_doubleroom502')
	RemoveIpl('int_hotel_doubleroom503')
	RemoveIpl('int_hotel_doubleroom504')
	RemoveIpl('int_hotel_doubleroom505')
	RemoveIpl('int_hotel_doubleroom506')
	RemoveIpl('int_hotel_room501')
	RemoveIpl('int_hotel_room502')
	RemoveIpl('int_hotel_room503')
	RemoveIpl('int_hotel_room504')
	RemoveIpl('int_hotel_room505')
	RemoveIpl('int_hotel_room506')
	RemoveIpl('int_hotel_room507')
	RemoveIpl('int_hotel_room508')
	RemoveIpl('int_hotel_room509')
	RemoveIpl('int_hotel_room510')
	RemoveIpl('int_hotel_room511')
	RemoveIpl('int_hotel_room512')
	RemoveIpl('int_hotel_room513')
	RemoveIpl('int_hotel_room514')
	RemoveIpl('int_hotel_room515')
	RemoveIpl('int_hotel_room516')
	RemoveIpl('int_hotel_room517')
	RemoveIpl('int_hotel_room518')
	RemoveIpl('int_hotel_room519')
	RemoveIpl('int_hotel_room520')
	RemoveIpl('int_hotel_room521')
	RemoveIpl('int_hotel_room522')
	RemoveIpl('int_hotel_room523')
	RemoveIpl('int_hotel_room524')

	RemoveIpl('int_hotel_corridor06')
	RemoveIpl('int_hotel_doubleroom601')
	RemoveIpl('int_hotel_doubleroom602')
	RemoveIpl('int_hotel_doubleroom603')
	RemoveIpl('int_hotel_doubleroom604')
	RemoveIpl('int_hotel_doubleroom605')
	RemoveIpl('int_hotel_doubleroom606')
	RemoveIpl('int_hotel_room601')
	RemoveIpl('int_hotel_room602')
	RemoveIpl('int_hotel_room603')
	RemoveIpl('int_hotel_room604')
	RemoveIpl('int_hotel_room605')
	RemoveIpl('int_hotel_room606')
	RemoveIpl('int_hotel_room607')
	RemoveIpl('int_hotel_room608')
	RemoveIpl('int_hotel_room609')
	RemoveIpl('int_hotel_room610')
	RemoveIpl('int_hotel_room611')
	RemoveIpl('int_hotel_room612')
	RemoveIpl('int_hotel_room613')
	RemoveIpl('int_hotel_room614')
	RemoveIpl('int_hotel_room615')
	RemoveIpl('int_hotel_room616')
	RemoveIpl('int_hotel_room617')
	RemoveIpl('int_hotel_room618')
	RemoveIpl('int_hotel_room619')
	RemoveIpl('int_hotel_room620')
	RemoveIpl('int_hotel_room621')
	RemoveIpl('int_hotel_room622')
	RemoveIpl('int_hotel_room623')
	RemoveIpl('int_hotel_room624')

	RemoveIpl('int_hotel_corridor07')
	RemoveIpl('int_hotel_doubleroom701')
	RemoveIpl('int_hotel_doubleroom702')
	RemoveIpl('int_hotel_doubleroom703')
	RemoveIpl('int_hotel_doubleroom704')
	RemoveIpl('int_hotel_doubleroom705')
	RemoveIpl('int_hotel_doubleroom706')
	RemoveIpl('int_hotel_room701')
	RemoveIpl('int_hotel_room702')
	RemoveIpl('int_hotel_room703')
	RemoveIpl('int_hotel_room704')
	RemoveIpl('int_hotel_room705')
	RemoveIpl('int_hotel_room706')
	RemoveIpl('int_hotel_room707')
	RemoveIpl('int_hotel_room708')
	RemoveIpl('int_hotel_room709')
	RemoveIpl('int_hotel_room710')
	RemoveIpl('int_hotel_room711')
	RemoveIpl('int_hotel_room712')
	RemoveIpl('int_hotel_room713')
	RemoveIpl('int_hotel_room714')
	RemoveIpl('int_hotel_room715')
	RemoveIpl('int_hotel_room716')
	RemoveIpl('int_hotel_room717')
	RemoveIpl('int_hotel_room718')
	RemoveIpl('int_hotel_room719')
	RemoveIpl('int_hotel_room720')
	RemoveIpl('int_hotel_room721')
	RemoveIpl('int_hotel_room722')
	RemoveIpl('int_hotel_room723')
	RemoveIpl('int_hotel_room724')
end

local function loadEtage1()
	RequestIpl('int_hotel_corridor01')
	RequestIpl('int_hotel_doubleroom101')
	RequestIpl('int_hotel_doubleroom102')
	RequestIpl('int_hotel_doubleroom103')
	RequestIpl('int_hotel_doubleroom104')
	RequestIpl('int_hotel_doubleroom105')
	RequestIpl('int_hotel_doubleroom106')
	RequestIpl('int_hotel_room101')
	RequestIpl('int_hotel_room102')
	RequestIpl('int_hotel_room103')
	RequestIpl('int_hotel_room104')
	RequestIpl('int_hotel_room105')
	RequestIpl('int_hotel_room106')
	RequestIpl('int_hotel_room107')
	RequestIpl('int_hotel_room108')
	RequestIpl('int_hotel_room109')
	RequestIpl('int_hotel_room110')
	RequestIpl('int_hotel_room111')
	RequestIpl('int_hotel_room112')
	RequestIpl('int_hotel_room113')
	RequestIpl('int_hotel_room114')
	RequestIpl('int_hotel_room115')
	RequestIpl('int_hotel_room116')
	RequestIpl('int_hotel_room117')
	RequestIpl('int_hotel_room118')
	RequestIpl('int_hotel_room119')
	RequestIpl('int_hotel_room120')
	RequestIpl('int_hotel_room121')
	RequestIpl('int_hotel_room122')
	RequestIpl('int_hotel_room123')
	RequestIpl('int_hotel_room124')
end

local function loadEtage2()
	RequestIpl('int_hotel_corridor02')
	RequestIpl('int_hotel_doubleroom201')
	RequestIpl('int_hotel_doubleroom202')
	RequestIpl('int_hotel_doubleroom203')
	RequestIpl('int_hotel_doubleroom204')
	RequestIpl('int_hotel_doubleroom205')
	RequestIpl('int_hotel_doubleroom206')
	RequestIpl('int_hotel_room201')
	RequestIpl('int_hotel_room202')
	RequestIpl('int_hotel_room203')
	RequestIpl('int_hotel_room204')
	RequestIpl('int_hotel_room205')
	RequestIpl('int_hotel_room206')
	RequestIpl('int_hotel_room207')
	RequestIpl('int_hotel_room208')
	RequestIpl('int_hotel_room209')
	RequestIpl('int_hotel_room210')
	RequestIpl('int_hotel_room211')
	RequestIpl('int_hotel_room212')
	RequestIpl('int_hotel_room213')
	RequestIpl('int_hotel_room214')
	RequestIpl('int_hotel_room215')
	RequestIpl('int_hotel_room216')
	RequestIpl('int_hotel_room217')
	RequestIpl('int_hotel_room218')
	RequestIpl('int_hotel_room219')
	RequestIpl('int_hotel_room220')
	RequestIpl('int_hotel_room221')
	RequestIpl('int_hotel_room222')
	RequestIpl('int_hotel_room223')
	RequestIpl('int_hotel_room224')
end

local function loadEtage3()
	RequestIpl('int_hotel_corridor03')
	RequestIpl('int_hotel_doubleroom301')
	RequestIpl('int_hotel_doubleroom302')
	RequestIpl('int_hotel_doubleroom303')
	RequestIpl('int_hotel_doubleroom304')
	RequestIpl('int_hotel_doubleroom305')
	RequestIpl('int_hotel_doubleroom306')
	RequestIpl('int_hotel_room301')
	RequestIpl('int_hotel_room302')
	RequestIpl('int_hotel_room303')
	RequestIpl('int_hotel_room304')
	RequestIpl('int_hotel_room305')
	RequestIpl('int_hotel_room306')
	RequestIpl('int_hotel_room307')
	RequestIpl('int_hotel_room308')
	RequestIpl('int_hotel_room309')
	RequestIpl('int_hotel_room310')
	RequestIpl('int_hotel_room311')
	RequestIpl('int_hotel_room312')
	RequestIpl('int_hotel_room313')
	RequestIpl('int_hotel_room314')
	RequestIpl('int_hotel_room315')
	RequestIpl('int_hotel_room316')
	RequestIpl('int_hotel_room317')
	RequestIpl('int_hotel_room318')
	RequestIpl('int_hotel_room319')
	RequestIpl('int_hotel_room320')
	RequestIpl('int_hotel_room321')
	RequestIpl('int_hotel_room322')
	RequestIpl('int_hotel_room323')
	RequestIpl('int_hotel_room324')
end

local function loadEtage4()
	RequestIpl('int_hotel_corridor04')
	RequestIpl('int_hotel_doubleroom401')
	RequestIpl('int_hotel_doubleroom402')
	RequestIpl('int_hotel_doubleroom403')
	RequestIpl('int_hotel_doubleroom404')
	RequestIpl('int_hotel_doubleroom405')
	RequestIpl('int_hotel_doubleroom406')
	RequestIpl('int_hotel_room401')
	RequestIpl('int_hotel_room402')
	RequestIpl('int_hotel_room403')
	RequestIpl('int_hotel_room404')
	RequestIpl('int_hotel_room405')
	RequestIpl('int_hotel_room406')
	RequestIpl('int_hotel_room407')
	RequestIpl('int_hotel_room408')
	RequestIpl('int_hotel_room409')
	RequestIpl('int_hotel_room410')
	RequestIpl('int_hotel_room411')
	RequestIpl('int_hotel_room412')
	RequestIpl('int_hotel_room413')
	RequestIpl('int_hotel_room414')
	RequestIpl('int_hotel_room415')
	RequestIpl('int_hotel_room416')
	RequestIpl('int_hotel_room417')
	RequestIpl('int_hotel_room418')
	RequestIpl('int_hotel_room419')
	RequestIpl('int_hotel_room420')
	RequestIpl('int_hotel_room421')
	RequestIpl('int_hotel_room422')
	RequestIpl('int_hotel_room423')
	RequestIpl('int_hotel_room424')
end

local function loadEtage5()
	RequestIpl('int_hotel_corridor05')
	RequestIpl('int_hotel_doubleroom501')
	RequestIpl('int_hotel_doubleroom502')
	RequestIpl('int_hotel_doubleroom503')
	RequestIpl('int_hotel_doubleroom504')
	RequestIpl('int_hotel_doubleroom505')
	RequestIpl('int_hotel_doubleroom506')
	RequestIpl('int_hotel_room501')
	RequestIpl('int_hotel_room502')
	RequestIpl('int_hotel_room503')
	RequestIpl('int_hotel_room504')
	RequestIpl('int_hotel_room505')
	RequestIpl('int_hotel_room506')
	RequestIpl('int_hotel_room507')
	RequestIpl('int_hotel_room508')
	RequestIpl('int_hotel_room509')
	RequestIpl('int_hotel_room510')
	RequestIpl('int_hotel_room511')
	RequestIpl('int_hotel_room512')
	RequestIpl('int_hotel_room513')
	RequestIpl('int_hotel_room514')
	RequestIpl('int_hotel_room515')
	RequestIpl('int_hotel_room516')
	RequestIpl('int_hotel_room517')
	RequestIpl('int_hotel_room518')
	RequestIpl('int_hotel_room519')
	RequestIpl('int_hotel_room520')
	RequestIpl('int_hotel_room521')
	RequestIpl('int_hotel_room522')
	RequestIpl('int_hotel_room523')
	RequestIpl('int_hotel_room524')
end

local function loadEtage6()
	RequestIpl('int_hotel_corridor06')
	RequestIpl('int_hotel_doubleroom601')
	RequestIpl('int_hotel_doubleroom602')
	RequestIpl('int_hotel_doubleroom603')
	RequestIpl('int_hotel_doubleroom604')
	RequestIpl('int_hotel_doubleroom605')
	RequestIpl('int_hotel_doubleroom606')
	RequestIpl('int_hotel_room601')
	RequestIpl('int_hotel_room602')
	RequestIpl('int_hotel_room603')
	RequestIpl('int_hotel_room604')
	RequestIpl('int_hotel_room605')
	RequestIpl('int_hotel_room606')
	RequestIpl('int_hotel_room607')
	RequestIpl('int_hotel_room608')
	RequestIpl('int_hotel_room609')
	RequestIpl('int_hotel_room610')
	RequestIpl('int_hotel_room611')
	RequestIpl('int_hotel_room612')
	RequestIpl('int_hotel_room613')
	RequestIpl('int_hotel_room614')
	RequestIpl('int_hotel_room615')
	RequestIpl('int_hotel_room616')
	RequestIpl('int_hotel_room617')
	RequestIpl('int_hotel_room618')
	RequestIpl('int_hotel_room619')
	RequestIpl('int_hotel_room620')
	RequestIpl('int_hotel_room621')
	RequestIpl('int_hotel_room622')
	RequestIpl('int_hotel_room623')
	RequestIpl('int_hotel_room624')
end

local function loadEtage7()
	RequestIpl('int_hotel_corridor07')
	RequestIpl('int_hotel_doubleroom701')
	RequestIpl('int_hotel_doubleroom702')
	RequestIpl('int_hotel_doubleroom703')
	RequestIpl('int_hotel_doubleroom704')
	RequestIpl('int_hotel_doubleroom705')
	RequestIpl('int_hotel_doubleroom706')
	RequestIpl('int_hotel_room701')
	RequestIpl('int_hotel_room702')
	RequestIpl('int_hotel_room703')
	RequestIpl('int_hotel_room704')
	RequestIpl('int_hotel_room705')
	RequestIpl('int_hotel_room706')
	RequestIpl('int_hotel_room707')
	RequestIpl('int_hotel_room708')
	RequestIpl('int_hotel_room709')
	RequestIpl('int_hotel_room710')
	RequestIpl('int_hotel_room711')
	RequestIpl('int_hotel_room712')
	RequestIpl('int_hotel_room713')
	RequestIpl('int_hotel_room714')
	RequestIpl('int_hotel_room715')
	RequestIpl('int_hotel_room716')
	RequestIpl('int_hotel_room717')
	RequestIpl('int_hotel_room718')
	RequestIpl('int_hotel_room719')
	RequestIpl('int_hotel_room720')
	RequestIpl('int_hotel_room721')
	RequestIpl('int_hotel_room722')
	RequestIpl('int_hotel_room723')
	RequestIpl('int_hotel_room724')
end

local function DisplayHelpText(text)
	BeginTextCommandDisplayHelp('STRING')
	AddTextComponentSubstringPlayerName(text)
	DisplayHelpTextFromStringLabel(0, 0, 1, -1)
end

_menuPool = NativeUI.CreatePool()
mainMenu = NativeUI.CreateMenu("Ascenseur", "~b~Etages")
_menuPool:Add(mainMenu)
_menuPool:RefreshIndex()

local function etape1()
	DoScreenFadeOut(1500)
	while IsScreenFadingOut() do Wait(10) end

	UnloadIpl()
end

local function etape2(currentetage, gotoetage)
	local ped = PlayerPedId()
	FreezeEntityPosition(ped, true)

	if gotoetage == 'Lobby' then
		nameEtage = 'Lobby01'
	else
		nameEtage = gotoetage .. string.sub(currentetage, -1)
	end

	local pos = Config.Zones[nameEtage].Spawn
	SetEntityCoords(ped, pos.x, pos.y, pos.z - 0.5, 1, 0, 0, 1)
	if pos.h then
		SetEntityHeading(ped, pos.h)
	end
	FreezeEntityPosition(ped, false)
	Wait(500)

	DoScreenFadeIn(1500)
	while IsScreenFadingIn() do Wait(10) end
end

local function AddMenuEtage(menu, currentEtage)
	if currentEtage ~= 'Lobby01' and currentEtage ~= 'Lobby02' and currentEtage ~= 'Lobby03' and currentEtage ~= 'Lobby04' then
		newitem7 = NativeUI.CreateItem(Config.Lang[Config.Locale].Lobby, '')
		menu:AddItem(newitem7)
	end

	if currentEtage ~= 'Etage71' and currentEtage ~= 'Etage72' and currentEtage ~= 'Etage73' and currentEtage ~= 'Etage74' then
		newitem6 = NativeUI.CreateItem(Config.Lang[Config.Locale].Etage7, '')
		menu:AddItem(newitem6)
    end

    menu.OnItemSelect = function(sender, item, index)
		if item == newitem6 then
           etape1()
		   loadEtage7()
		   etape2(currentEtage,"Etage7")
		elseif item == newitem7 then
			etape1()
			etape2(currentEtage,"Lobby")
        end
		menu:Visible(false)
    end
end

local function refreshMenu()
	_menuPool = NativeUI.CreatePool()
	mainMenu = NativeUI.CreateMenu(Config.Lang[Config.Locale]["elevator"], Config.Lang[Config.Locale]["lfloor"])
	_menuPool:Add(mainMenu)
	_menuPool:MouseControlsEnabled (false)
	_menuPool:MouseEdgeEnabled (false)
	_menuPool:ControlDisablingEnabled(false)

	_menuPool:RefreshIndex()
	return mainMenu
end

CreateThread(function()
	UnloadIpl()

    while true do
        Wait(0)
        _menuPool:ProcessMenus()
		local coords = GetEntityCoords(PlayerPedId())
		for k, v in pairs(Config.Zones) do
			local distance = #(coords - vec3(v.Marker.x, v.Marker.y, v.Marker.z))

			if Config.showMarker and distance <= Config.DrawDistance then
				DrawMarker(1, v.Marker.x, v.Marker.y, v.Marker.z, 0, 0, 0, 0, 0, 0, 2.01, 2.01, 0.55, 10, 255, 10, 65, 0, 0, 0, 0)
			end

			if distance <= 1.5 then
				DisplayHelpText(Config.Lang[Config.Locale].openMenu)
				if IsControlJustPressed(0, Config.OpenMenuKey) then
					mainMenu = refreshMenu()
					AddMenuEtage(mainMenu, k)
					mainMenu:Visible(not mainMenu:Visible())
				end
			end
		end
    end
end)